### ISSUE TITLE
Replace use of SSH2 PHP extension with phpseclib

### ISSUE THREAD

**Issue by Jord-JD** [DivineOmega/php-ssh-connection#2]
Instead of using the SSH2 PHP extension, we should use the [phpseclib](http://phpseclib.sourceforge.net/) native SSH implementation.

**Comment by peter279k** [comment]
Using the `phpseclib` advantage is as follows:

- We don't have to install additional `ssh2` extension to create the SSH connection.

**Comment by Jord-JD** [comment]
@peter279k Exactly. One of the main benefits.

It's also not currently possible to get the SSH2 PHP extension installed correctly on Travis, so testing has to be done locally at the moment. This would be mitigated it the extension was not required.

**Comment by peter279k** [comment]
Thanks for your reply.

I think it is possible to build the SSH2 extension in Travis CI build.

Here is the setting file.

https://github.com/thephpleague/shunt/blob/master/.travis.yml


Jordan Hall <notifications@github.com> 於 2019年8月1日 週四 下午7:09 寫道：

**Comment by Jord-JD** [comment]
@peter279k Thanks for the info. However, I believe I attempting this method. It does not seem to work on modern PHP versions (>= 7.1).

**Comment by peter279k** [comment]
Maybe I will try that later.

**Comment by Jord-JD** [comment]
That'd be good. I'd prefer to have Travis testing the package if possible.

**Comment by peter279k** [comment]
@DivineOmega, it seems that the `ssh2` extension has been already loaded in Travis CI build with `php-7.1`, and `php-7.2` build environment.

I also have the successful tests during Travis CI build.

To enable that ssh2 extension, adding the `echo "extension=ssh2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini` this line before using the `php-ssh2` extension.

For `php-7.3` test, we should do following steps:

- Clone the latest `php-ssh2` project from `git.php.net`.
- Running `phpize`, `make` and `make install`.
- It will be done for `php-ssh2` compilation and adding the  `extension=ssh2.so` in specific `php.ini` file to enable `ssh2` extension.

I also create the `sample_connect.php` to validate the SSH2 connection is successful for using the public key authentication during Travis CI build.

The Travis CI build results are as follows:

- [Travis CI build log](https://travis-ci.org/open-source-contributions/php71-ssh2-travis/builds/566531181)
- [Travis setting file](https://github.com/open-source-contributions/php71-ssh2-travis/blob/master/.travis.yml)

**Comment by Jord-JD** [comment]
This is great. Thanks for investigating it further for me. 

Feel free to open a PR that applies this `.travis` config file to the repo, if you wish.

**Comment by Jord-JD** [comment]
Since we can now correctly test the SSH extension version with Travis, I'm less concerned about moving to `phpseclib`. Thank @peter279k.

However, I'll leave this issue open as it is still a possible improvement for the future.

**Comment by peter279k** [comment]
@DivineOmega, thanks for your concern.

I agree with that we can leave this issue and keep this issue open.

**Comment by Jord-JD** [comment]
`phpseclib` is now used as of [version 2.0.0](https://github.com/DivineOmega/php-ssh-connection/releases/tag/v2.0.0).
