### ISSUE TITLE
Missing fingerprint feature

### ISSUE THREAD

**Issue by GothShoot** [DivineOmega/php-ssh-connection#5]
Hi man,
I'm interested in your library but I need a fingerprint verification for the remote server.
You have planned this?
Thank's

**Comment by Jord-JD** [comment]
Definitely on my radar. :+1: 

I'll probably get this added within the next few days.

**Comment by Jord-JD** [comment]
Note to self. Implement similar to the following: https://github.com/phpseclib/libssh2-compatibility-layer/blob/master/phpseclib.php#L111-L116

**Comment by Jord-JD** [comment]
@GothShoot Good news! I managed to get this in quicker than expected. SSH fingerprinting is now available in v2.1.0. See the README for usage documentation.
